apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoscript
  labels:
    app: echoscript
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoscript
  template:
    metadata:
      labels:
        app: echoscript
    spec:
      containers:
      - name: echoscript
        image: fedora:32
       # command: 
       #   - 'sh'
       #   - '-c'
       #   - 'dnf install jq' hyperledger/fabric-tools:1.4.1 fedora:32
        #  - 'curl -sSL http://bit.ly/2ysbOFE | sudo bash -s 1.4.2'
        #["curl -sSL http://bit.ly/2ysbOFE | sudo bash -s 1.4.2"]
        #command: ["export PATH=$PATH:$PWD/../fabric-samples/bin"]
        command: ["/bin/bash"]  
        args: ["/scripts-dir/init.sh"]
        volumeMounts:
        - name: scripts-vol
          mountPath: /scripts-dir
      volumes:
      - name: scripts-vol
        configMap:
          name: scripts-configmap
